---
grails:
    profile: web
    codegen:
        defaultPackage: saas.service
    env: production
server:
    port: 9000

info:
    app:
        name: 'goods-service'
        version: '$appversion'
        grailsVersion: '3.0.3'
spring:
    groovy:
        template:
            check-template-location: false
            
endpoints:
    jmx:
        enabled: false
        unique-names: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
        json:
            default:
                deep: true
        default:
            circular:
                reference:
                    behaviour: "INSERT_NULL"
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

hibernate:
    cache:
        queries: false

---
dataSources:
    dataSource:
        pooled: true
        jmxExport: false
        driverClassName: com.mysql.jdbc.Driver
        dbCreate: none
        properties:
            jmxEnabled: false
            initialSize: 5
            maxActive: 100
            minIdle: 5
            maxIdle: 25
            maxWait: 10000
            maxAge: 600000
            timeBetweenEvictionRunsMillis: 5000
            minEvictableIdleTimeMillis: 60000
            validationQuery: SELECT 1
            validationQueryTimeout: 3
            validationInterval: 15000
            testOnBorrow: true
            testWhileIdle: true
            testOnReturn: false
            jdbcInterceptors: ConnectionState;StatementCache(max=200)
            defaultTransactionIsolation: 2 #java.sql.Connection.TRANSACTION_READ_COMMITTED
            removeAbandoned: true
            removeAbandonedTimeout: 300
---
environments:
    production:
        properties: pro.properties
        dataSources:
            dataSource:
                username: $goods_db_user
                password: $goods_db_pwd
                url: jdbc:mysql://$goods_db_ip:$goods_db_port/goods-db
