server:
    port: 7000

endpoints:
    jmx:
        enabled: false
        unique-names: true
        version: '$appversion'
---
spring:
    datasource:
        name: saas        
        url: jdbc:mysql://$saas_db_ip:$saas_db_port/saas-db
        username: $saas_db_user
        password: $saas_db_pwd
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 200
        initialSize: 20
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20    
---
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: service.router.domain
